<!-- FOOTER -->
			<footer id="footer">
				<div class="container">

					<div class="row">
						
						<div class="col-md-3">
							<!-- Footer Logo -->
							<img class="footer-logo" src="assets/images/logo-footer.png" alt="" />

							<!-- Small Description -->
							<!--<p>Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p>-->

							<!-- Contact Address -->
							<address>
								<ul class="list-unstyled">
									<li class="footer-sprite address">
										344041<br>
										ул Доватора 118а<br>
										Ростов-На-Дону Россия<br>
									</li>
									<li class="footer-sprite phone">
										Тел:  +7-863-301-07-70
									</li>
									<li class="footer-sprite email">
										<a href="mailto:welcome@lvs.tel">welcome@lvs.tel</a>
									</li>
								</ul>
							</address>
							<!-- /Contact Address -->

						</div>

						<div class="col-md-3">

							<!-- Latest Blog Post -->
							<h4 class="letter-spacing-1">Новости</h4>
							<ul class="footer-posts list-unstyled">
								<li>
									<a href="#">Мы запустили сайт</a>
									<small>29 июля 2016</small>
								</li>
								
							</ul>
							<!-- /Latest Blog Post -->

						</div>

						<div class="col-md-2">

							<!-- Links -->
							<h4 class="letter-spacing-1">Обзор сайта</h4>
							<ul class="footer-links list-unstyled">
								<li><a href="./index.shtml">Главная страница</a></li>
								<li><a href="#">О компании</a></li>
								<li><a href="./page-contact-3.shtml">Контакты</a></li>
							</ul>
							<!-- /Links -->

						</div>

						<div class="col-md-4">

							
							<h4 class="letter-spacing-1">Всегда на связи</h4>
							<p>Подпишитесь на рассылку новостей</p>

							<form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
									<input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
									<span class="input-group-btn">
										<button class="btn btn-success" type="submit">Subscribe</button>
									</span>
								</div>
							</form>
							
							<div class="margin-top-20">
								<a href="#" class="social-icon social-icon-border social-facebook pull-left" data-toggle="tooltip" data-placement="top" title="Facebook">

									<i class="icon-facebook"></i>
									<i class="icon-facebook"></i>
								</a>

								<a href="#" class="social-icon social-icon-border social-twitter pull-left" data-toggle="tooltip" data-placement="top" title="Twitter">
									<i class="icon-twitter"></i>
									<i class="icon-twitter"></i>
								</a>

								<a href="#" class="social-icon social-icon-border social-gplus pull-left" data-toggle="tooltip" data-placement="top" title="Google plus">
									<i class="icon-gplus"></i>
									<i class="icon-gplus"></i>
								</a>

								<a href="#" class="social-icon social-icon-border social-linkedin pull-left" data-toggle="tooltip" data-placement="top" title="Linkedin">
									<i class="icon-linkedin"></i>
									<i class="icon-linkedin"></i>
								</a>

								<a href="#" class="social-icon social-icon-border social-rss pull-left" data-toggle="tooltip" data-placement="top" title="Rss">
									<i class="icon-rss"></i>
									<i class="icon-rss"></i>
								</a>
					
							</div>

						</div>  <!-- Social networks  -->

					</div>

				</div>

				<div class="copyright">
					<div class="container">
						<ul class="pull-right nomargin list-inline mobile-block">
							<li><a href="#">Прочие условия</a></li>
							<li>&bull;</li>
							<li><a href="#">Конфиденциальность</a></li>
						</ul>
						&copy; Все права зарезервированы "ООО Слаботочные системы"
					</div>
				</div>
			</footer>
			<!-- /FOOTER -->