<div id="slidetop">

			<div class="container">
				
				<div class="row">

					<div class="col-md-4">
						<h6><i class="icon-heart"></i> Слаботочные системы</h6>
						<ul class="list-unstyled">
							<li><a href="#"><i class="fa fa-angle-right"></i> Монтаж сетей передачи данных любой сложности.</a></li>
							<li><a href="#"><i class="fa fa-angle-right"></i> Разработка и монтаж систем интеллектуального видеонаблюдения со стандартным и расширенным функционалом. </a></li>
							<li><a href="#"><i class="fa fa-angle-right"></i> Установка и обслуживания сетей противопожарной и охранной сигнализации</a></li>
							<li><a href="#"><i class="fa fa-angle-right"></i> Обслуживание серверов и рабочих станций Linux/Windows</a></li>
							<li><a href="#"><i class="fa fa-angle-right"></i> Разработка и внедрение программного обеспечения.
</a></li>
							<li><a href="#"><i class="fa fa-angle-right"></i> Обслуживание принтеров и копировальных аппаратов.
</a></li>
						</ul>
						
					</div>

					<div class="col-md-4">
						<h6><i class="icon-attachment"></i> О Компании и людях</h6>
						<p>В ООО «Слаботочные Системы» работает команда квалифицированных профессионалов, которые неустанно совершенствуют уровень своих знаний и навыков. Ведь современные технологии постоянно развиваются, появляется новое оборудование и улучшается качество передачи информации. Поэтому мы систематически повышаем уровень квалификации персонала, предоставляя клиентам инновационные решения. Нам важно, чтобы слаботочные системы вашей организации работали быстро, слаженно и эффективно.</p><p>Индивидуальный подход к каждому заказчику. Мы всегда обсуждаем детали будущего сотрудничества с клиентом и воплощаем задуманное в соответствии с его пожеланиями, требованиями корпоративных и медународных стандартов. Если вы хотите заказать системную интеграцию у профессионалов, которые учитывают ваше мнение – обращайтесь в ООО «Слаботочные Системы».</p>
					</div>

					<div itemscope itemtype="http://schema.org/Organization" class="col-md-4">
						<h5><span itemprop="name">ООО «Слаботочные Системы»</span></h5>
						<h6><i class="icon-envelope"></i> Контакты</h6>
						
						<ul class="list-unstyled" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
							<li><b>Адрес:</b> <span itemprop="postalCode">344041</span>, <span itemprop="streetAddress">ул Доватора 118а</span>, <br /> <span itemprop="addressLocality">Ростов-на-Дону Россия</span></li>
							<li><b>Тел:</b> <span itemprop="telephone">7-863-301-07-70</span></li>
							<li><b>Email:</b> <a href="mailto:welcome@lvs.telm"> <span itemprop="email">welcome@lvs.tel</span></a></li>
						</ul>

					</div>

				</div>

			</div>

			<a class="slidetop-toggle" href="#"><!-- toggle button --></a>

		</div>